reset;

model C:\Users\jwsjt\Desktop\acrp-lib-master\Code\NC_ACRP_Cluster.mod;

problem NC_ACRP: Obj,q,theta,vrx,vry,z,bin11,bin12,cvrx,cvry,bin311,bin312,bin321,bin322,bin331,bin332,bin341,bin342;
option solver "C:\Users\jwsjt\Desktop\acrp-lib-master\CoinAll-1.6.2-win32-cl15ifort11.1\bin\couenne.exe";

data C:\Users\jwsjt\Desktop\acrp-lib-master\Data\RCP_Instances\RCP_Instances\RCP_10_3.dat;		
	
let A := 1..n;
let C := A;
let wd := 0.5;

# pre-processing of variables bounds and coefficients
include C:\Users\jwsjt\Desktop\acrp-lib-master\Code\PreprocessingCluster.run;

let C := A diff C2;

problem NC_ACRP;
#solve NC_ACRP;

for {i in C1}{
let v0[i] := q[i]*v0[i];
let cap[i] := theta[i]+cap[i];
}

display q,theta,Obj, v0;

let C := A diff C1;

problem NC_ACRP;
#solve NC_ACRP;

for {i in C2}{
let v0[i] := q[i]*v0[i];
let cap[i] := theta[i]+cap[i];
}

display q,theta,Obj, v0, cap;

let C := C1;

#include C:\Users\jwsjt\Desktop\acrp-lib-master\Code\PreprocessingCluster.run;
