reset;

#model C:\Users\jwsjt\Desktop\acrp-lib-master\Code\NC_ACRP_Cluster.mod;
model C:\Users\user\Documents\THESIS\THESIS2021\Code\NC_ACRP_Cluster.mod

problem NC_ACRP: Obj,q,theta,vrx,vry,z,bin11,bin12,cvrx,cvry,bin311,bin312,bin321,bin322,bin331,bin332,bin341,bin342;
#option solver "C:\Users\jwsjt\Desktop\acrp-lib-master\CoinAll-1.6.2-win32-cl15ifort11.1\bin\couenne.exe";
option solver "C:\Users\user\Documents\THESIS\THESIS2021\CoinAll-1.6.2-win32-cl15ifort11.1\bin\couenne.exe";

data C:\Users\user\Documents\THESIS\THESIS2021\Data\RCP_Instances\RCP_Instances\RCP_10_9.dat;		
	
let A := 1..n;
let C := A;
let wd := 0.5;
let nc := 5;

# pre-processing of variables bounds and coefficients
#include C:\Users\jwsjt\Desktop\acrp-lib-master\Code\PreprocessingCluster.run;
include C:\Users\user\Documents\THESIS\THESIS2021\Code\PreprocessingTest.run;
include C:\Users\user\Documents\THESIS\THESIS2021\Code\Clustering.run;

#Create Set of Clusters, iterate over set - if card(C1) >0 => solve else continue
let C := C1;

problem NC_ACRP;
solve NC_ACRP;

for {i in C}{
let v0[i] := q[i]*v0[i];
let cap[i] := theta[i]+cap[i];
}

display q,theta,Obj, v0;

let C := C2;

problem NC_ACRP;
solve NC_ACRP;

for {i in C}{
let v0[i] := q[i]*v0[i];
let cap[i] := theta[i]+cap[i];
}

display q,theta,Obj, v0, cap;

#let C := C3;
#
#problem NC_ACRP;
#solve NC_ACRP;
#
#for {i in C}{
#let v0[i] := q[i]*v0[i];
#let cap[i] := theta[i]+cap[i];
#}



let C := A;

#Loop over C and count/identify conflicts, any conflicts are with aircraft outside the same cluster
#(potentially) Recluster to maintain original clusters where possible, adding additional aircraft in conflict

include C:\Users\user\Documents\THESIS\THESIS2021\Code\Clustering.run;

let C := C1;

problem NC_ACRP;
solve NC_ACRP;

for {i in C}{
let v0[i] := q[i]*v0[i];
let cap[i] := theta[i]+cap[i];
}

display q,theta,Obj, v0;

let C := C2;

problem NC_ACRP;
solve NC_ACRP;

for {i in C}{
let v0[i] := q[i]*v0[i];
let cap[i] := theta[i]+cap[i];
}

display q,theta,Obj, v0, cap;
let C := A;

include C:\Users\user\Documents\THESIS\THESIS2021\Code\Clustering.run;